SHARES = 10
ACCOUNTS_CSV_PATH = 'accounts.csv'
CAPITALS = [{"code": "19000", "id": 1287, "name": "AAKASH CAPITAL LIMITED"},
            {"code": "20600", "id": 1315, "name": "AAKASHBHAIRAB SECURITIES LIMITED"},
            {"code": "13200", "id": 128, "name": "ABC SECURITIES PRIVATE LIMITED"},
            {"code": "12300", "id": 129, "name": "AGRAWAL SECURITIES PRIVATE LIMITED"},
            {"code": "17200", "id": 130, "name": "AGRICULTURAL DEVELOPMENT BANK LIMITED"},
            {"code": "11900", "id": 131, "name": "ARYATARA INVESTMENT AND SECURITIES PRIVATE LIMITED"},
            {"code": "15600", "id": 132, "name": "ASHUTOSH BROKERAGE AND SECURITIES PRIVATE LIMITED"},
            {"code": "17500", "id": 201, "name": "ASIAN CAPITAL LIMITED"},
            {"code": "14700", "id": 133, "name": "ASIAN SECURITIES PRIVATE LIMITED"},
            {"code": "19100", "id": 1298, "name": "BHOLE GANESH SECURITIES LIMITED."},
            {"code": "15000", "id": 135, "name": "BHRIKUTI STOCK BROKING COMPANY PRIVATE LIMITED"},
            {"code": "20700", "id": 1314, "name": "BLUE CHIP SECURITIES LIMITED"},
            {"code": "20900", "id": 1318, "name": "CAPITAL HUB PVT. LTD."},
            {"code": "19500", "id": 1292, "name": "CAPITAL MAX SECURITIES LIMITED"},
            {"code": "11700", "id": 137, "name": "CITIZENS BANK INTERNATIONAL LIMITED"},
            {"code": "10100", "id": 138, "name": "CIVIL CAPITAL MARKET LIMITED"},
            {"code": "13300", "id": 139, "name": "CREATIVE SECURITIES PRIVATE LIMITED"},
            {"code": "13400", "id": 140, "name": "CRYSTAL KANCHANJUNGHA SECURITIES PVT. LTD"},
            {"code": "12000", "id": 141, "name": "DAKSHINKALI INVESTMENT AND SECURITIES PRIVATE LIMITED"},
            {"code": "14500", "id": 142, "name": "DEEVYAA  SECURITIES & STOCK HOUSE PRIVATE LIMITED"},
            {"code": "11300", "id": 143, "name": "DIPSHIKHA DHITOPATRA KAROBAR COMPANY (P.) LTD."},
            {"code": "14900", "id": 144, "name": "DYNAMIC MONEY MANAGERS SECURITIES PRIVATE LIMITED"},
            {"code": "20300", "id": 1311, "name": "ELITE MERCHANT CAPITAL LIMITED"},
            {"code": "19800", "id": 1305, "name": "ELITE STOCK HOUSE LIMITED"},
            {"code": "10800", "id": 145, "name": "EVEREST BANK LTD."},
            {"code": "17600", "id": 153, "name": "GARIMA CAPITAL LIMITED"},
            {"code": "12200", "id": 151, "name": "GLOBAL IME BANK LIMITED"},
            {"code": "11100", "id": 134, "name": "GLOBAL IME BANK LIMITED"},
            {"code": "11200", "id": 146, "name": "GLOBAL IME CAPITAL LIMITED"},
            {"code": "16200", "id": 147, "name": "GUHESWORI MERCHANT BANKING & FINANCE LIMITED"},
            {"code": "18000", "id": 681, "name": "GURKHAS FINANCE LIMITED"},
            {"code": "20500", "id": 1317, "name": "HATEMALO FINANCIAL SERVICES PRIVATE LIMITED"},
            {"code": "19600", "id": 1297, "name": "HIMALAYAN BROKERAGE COMPANY LIMITED"},
            {"code": "17700", "id": 148, "name": "HIMALAYAN CAPITAL LIMITED"},
            {"code": "17400", "id": 149, "name": "ICFC FINANCE LIMITED"},
            {"code": "13100", "id": 150, "name": "IMPERIAL SECURITIES COMPANY LIMITED"},
            {"code": "20000", "id": 1308, "name": "INDEX SECURITIES LIMITED"},
            {"code": "20800", "id": 1316, "name": "INDIRA SECURITIES PVT. LTD."},
            {"code": "19900", "id": 1306, "name": "INFINITY SECURITIES LIMITED"},
            {"code": "17900", "id": 402, "name": "JYOTI BIKASH BANK LIMITED"},
            {"code": "20100", "id": 1309, "name": "KALASH STOCK MARKET PVT. LTD."},
            {"code": "18700", "id": 1271, "name": "KALIKA SECURITIES PVT. LTD."},
            {"code": "18200", "id": 1182, "name": "KAMANA SEWA BIKAS BANK LIMITED."},
            {"code": "14300", "id": 154, "name": "KOHINOOR INVESTMENT & SECURITIES PRIVATE LIMITED"},
            {"code": "16300", "id": 168, "name": "KUMARI BANK LIMITED"},
            {"code": "15200", "id": 156, "name": "KUMARI BANK LIMITED"},
            {"code": "10700", "id": 157, "name": "LAXMI CAPITAL MARKET LTD."},
            {"code": "13800", "id": 158, "name": "LINCH STOCK MARKET  LIMITED"},
            {"code": "16100", "id": 159, "name": "MACHHAPUCHCHHRE BANK LIMITED"},
            {"code": "14100", "id": 155, "name": "MACHHAPUCHCHHRE CAPITAL LIMITED"},
            {"code": "21400", "id": 1327, "name": "MACHHAPUCHCHHRE SECURITIES LTD."},
            {"code": "16700", "id": 160, "name": "MAHALAXMI BIKAS BANK LIMITED"},
            {"code": "18900", "id": 1281, "name": "MANJUSHREE FINANCE LIMITED"},
            {"code": "13600", "id": 161, "name": "MARKET SECURITIES EXCHANGE COMPANY PVT. LTD"},
            {"code": "21600", "id": 1329, "name": "MILKY WAY SHARE BROKER COMPANY LTD."},
            {"code": "19700", "id": 1295, "name": "MIYO SECURITIES PRIVATE LIMITED"},
            {"code": "21100", "id": 1325, "name": "MONEY WORLD SHARE EXCHANGE PVT. LTD."},
            {"code": "12500", "id": 199, "name": "MUKTINATH CAPITAL LIMITED"},
            {"code": "15900", "id": 163, "name": "NAASA SECURITIES COMPANY LTD"},
            {"code": "16800", "id": 198, "name": "NABIL BANK LIMITED"},
            {"code": "15100", "id": 166, "name": "NABIL BANK LIMITED"},
            {"code": "10400", "id": 164, "name": "NABIL INVESTMENT BANKING LTD."},
            {"code": "20400", "id": 1320, "name": "NAGARIK STOCK DEALER COMPANY LIMITED"},
            {"code": "15700", "id": 167, "name": "NEPAL BANK LIMITED"},
            {"code": "15500", "id": 169, "name": "NEPAL DP LIMITED"},
            {"code": "16400", "id": 165, "name": "NEPAL LIFE CAPITAL LIMITED"},
            {"code": "15300", "id": 170, "name": "NEPAL SBI BANK LIMITED"},
            {"code": "11500", "id": 171, "name": "NEPAL STOCK HOUSE PRIVATE LIMITED"},
            {"code": "13700", "id": 174, "name": "NIC ASIA BANK LIMITED"},
            {"code": "10200", "id": 172, "name": "NIMB ACE CAPITAL LIMITED"},
            {"code": "17300", "id": 162, "name": "NIMB ACE CAPITAL LIMITED"},
            {"code": "10600", "id": 173, "name": "NIMB ACE CAPITAL LIMITED"},
            {"code": "11000", "id": 175, "name": "NMB CAPITAL LIMITED"},
            {"code": "11800", "id": 176, "name": "ONLINE SECURITIES LIMITED"},
            {"code": "21200", "id": 1324, "name": "OPAL SECURITIES INVESTMENT PVT. LTD."},
            {"code": "17000", "id": 177, "name": "OXFORD SECURITIES PVT. LTD."},
            {"code": "21300", "id": 1328, "name": "PAHI INVESTMENT PVT. LTD."},
            {"code": "13900", "id": 178, "name": "PRABHU BANK LIMITED"},
            {"code": "16000", "id": 136, "name": "PRABHU BANK LIMITED"},
            {"code": "12600", "id": 179, "name": "PRABHU CAPITAL LIMITED"},
            {"code": "14800", "id": 180, "name": "PREMIER SECURITIES COMPANY LIMITED"},
            {"code": "16900", "id": 181, "name": "PRIME COMMERCIAL BANK LIMITED"},
            {"code": "15400", "id": 152, "name": "PRIME COMMERCIAL BANK LIMITED"},
            {"code": "12800", "id": 182, "name": "PRIMO SECURITIES PRIVATE LIMITED"},
            {"code": "18600", "id": 1270, "name": "PROGRESSIVE FINANCE LIMITED"},
            {"code": "19400", "id": 1293, "name": "PROPERTY WIZARD LIMITED"},
            {"code": "16600", "id": 183, "name": "PROVIDENT MERCHANT BANKING LIMITED"},
            {"code": "16500", "id": 184, "name": "RBB MERCHANT BANKING LIMITED"},
            {"code": "21500", "id": 1326, "name": "S.P.S.A. SECURITIES LTD."},
            {"code": "18100", "id": 1080, "name": "SAMPANNA CAPITAL AND ADVISORY NEPAL LIMITED"},
            {"code": "14400", "id": 185, "name": "SANI SECURITIES COMPANY LIMITED"},
            {"code": "15800", "id": 186, "name": "SANIMA BANK LTD"},
            {"code": "11600", "id": 187, "name": "SECURED SECURITIES LIMITED"},
            {"code": "12700", "id": 188, "name": "SEWA SECURITIES PRIVATE LIMITED"},
            {"code": "18400", "id": 1189, "name": "SHANGRI-LA DEVELOPMENT BANK LIMITED"},
            {"code": "19200", "id": 1294, "name": "SHAREPRO SECURITIES PVT.LTD."},
            {"code": "18500", "id": 1196, "name": "SHINE RESUNGA DEVELOPMENT BANK LIMITED"},
            {"code": "18800", "id": 1274, "name": "SHREE INVESTMENT AND FINANCE CO. LTD."},
            {"code": "12900", "id": 189, "name": "SHREE KRISHNA SECURITIES LIMITED"},
            {"code": "10900", "id": 190, "name": "SIDDHARTHA CAPITAL LIMITED"},
            {"code": "14600", "id": 191, "name": "SIPLA SECURITIES PRIVATE LIMITED"},
            {"code": "13000", "id": 192, "name": "SOUTH ASIAN BULLS PRIVATE LIMITED"},
            {"code": "14000", "id": 193, "name": "SRI HARI SECURITIES PVT. LTD."},
            {"code": "21000", "id": 1319, "name": "STOXKARTS SECURITIES LIMITED"},
            {"code": "20200", "id": 1310, "name": "SUBHAKAMANA SECURITIES PVT. LTD."},
            {"code": "14200", "id": 194, "name": "SUMERU  SECURITIES  PRIVATE  LIMITED"},
            {"code": "19300", "id": 1296, "name": "SUN SECURITIES PVT. LTD."},
            {"code": "17800", "id": 370, "name": "SUNDHARA SECURITIES LIMITED"},
            {"code": "12400", "id": 195, "name": "SUNRISE CAPITAL LIMITED"},
            {"code": "18300", "id": 1186, "name": "SWARNALAXMI SECURITIES PVT. LTD."},
            {"code": "11400", "id": 196, "name": "TRISHAKTI SECURITIES PUBLIC LIMITED"},
            {"code": "17100", "id": 197, "name": "TRISHUL SECURITIES & INVESTMENT LIMITED"},
            {"code": "13500", "id": 200, "name": "VISION SECURITIES PVT. LTD"}]
